### ISSUE TITLE
Need more tests for capes

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#102]
[test coverage is really bad](https://coveralls.io/builds/1960703/source?filename=routes%2Fcapes.js)

**Comment by Jake0oo0** [comment]
If you specifically mean that file, it's an issue with all of the routes, mainly because of the etag code.

**Comment by jomo** [comment]
It seems like there is [no test](https://coveralls.io/builds/1972054/source?filename=routes%2Fcapes.js#L46) that would actually return an image
