### ISSUE TITLE
Getting slower and slower

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#104]
I took a look at our response times yesterday on heroku.

Average response time short after startup: 31ms
Average response time few hours later: 689ms

I doubt the number of requests/s increased a lot during that time, but we had *a lot* more traffic than we ever had before this weekend. Now that traffic decreased, response time also went down again.

I noticed this a few days ago and reverted from master to @b88db00b97e1fc0e8475296783c77c72a04709c2 - that is before the recent changes with HTTP 429 handling and caching changes. Reverting didn't help, however.

Maybe we don't have enough CPU or RAM on heroku and that slows it down when we have that many requests.

**Comment by Jake0oo0** [comment]
Someone mentioned to me that quality is continuing to degrade over the past few days, so I went ahead and reverted to the last build before this update. So ~2 months ago. We'll need to figure out what's causing these issues, and _thoroughly_ test it before releasing it. @jomo

**Comment by jomo** [comment]
I had already reverted to @de5bad8702ec622d70fb26b780892880e96d203c from 12 days ago :stuck_out_tongue_closed_eyes:

**Comment by Jake0oo0** [comment]
Was still having issues :p

**Comment by jomo** [comment]
See also: #66.
To reproduce the slowness we had on heroku, we could probably run `test/bulk.sh` for some minutes (hours?) in a loop until response time gets really slow.

**Comment by jomo** [comment]
I'm closing this. Every now and then we get slow response times. It's just a few requests and only for a few seconds (or minutes at most). And it's always *far* below 0.1% of our requests, I think that's acceptable and it will most probably go away with #66 and #79 anyway.
