### ISSUE TITLE
dokku container randomly crashes

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#105]
I have noticed a few times that the dokku container just wasn't running anymore.
`docker ps` lists all running containers. Redis always seems to be running, but our app is suddenly gone and we need to run `dokku rebuild crafatar` to restart the app.

The last time this happened I checked both output and error logs, but nothing special there. It just stopped.
This is very confusing to me because even if the (currently 1) worker thread crashed, it would be respawned. If that fails too and the whole app crashes, `forever` should restart it as well, like this:
```
error: Forever detected script exited with code: 1
error: Script restart attempt #1
```

We're often running close to the Memory limit, but there's another GB of swap -- I don't think that would cause a crash like this.

**Comment by connor4312** [comment]
If you're using file-based logging, or anything other than stderr for logging, exceptions will not necessarily be caught in the log as your app may halt before the error is finished being written.

You'd want to listen for an [uncaughtException](https://nodejs.org/api/process.html#process_event_uncaughtexception) in your app. Log the exception, and ensure it actually is logged before shutting down the process.

**Comment by jomo** [comment]
This doesn't seem to be happening anymore, I'll reopen if it does.
