### ISSUE TITLE
Resolve names to UUIDs

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#106]
We currently use Mojang's skin endpoint to resolve `name -> image`.

This leads to a few problems:

0. That endpoint will eventually be shut down sooner or later.
0. We're caching the same user twice (`name -> image` + `UUID -> image`)
0. We can't determine the fallback type (alex/steve) if we don't know the UUID

----

I think it would be better to resolve the name to a UUID and only store `name -> UUID` & `UUID -> image`.

**Comment by Jake0oo0** [comment]
@Jomo isn't the username ---> UUID API rate limited? I think it's a pretty strict one too...

**Comment by jomo** [comment]
it is, that's why we store `name -> UUID` in redis and then `UUID -> image hash`.
When we get a request for a username, we look up the UUID in redis (or request it, if not found). We then use that UUID to get the image, also from redis as we already do.

**Comment by Jake0oo0** [comment]
I know we cache it, but the API is ip limited to 600 requests per 10 minutes according to the protocol wiki. It doesn't specify the limit for the username to UUID endpoint, but I assume it's the same. Isn't there a good chance that we would reach that limit?

**Comment by jomo** [comment]
Well :shit:. With ~50 *uncached* requests per second we most certainly hit that limit fairly quick.
What now?

**Comment by Jake0oo0** [comment]
This Mojang Clusterfuck tag is pretty fitting for so many of the issues we have...

**Comment by jomo** [comment]
> the API is ip limited to 600 requests per 10 minutes according to the protocol wiki

I tested and can confirm this.

600/10mins means 1/s.
I had a bit of discussion about this on IRC recently. The only semi-solution to this is queuing up requests and then do a bulk request, which allows 100 names per request.
That API has the same limit, so we could do 100 requests per second.
We would need to queue up requests up to 1 second, then send the request to mojang (which is obviously slower), then get the skin for each and then answer all the requests.

I think this would be very slow, and it doesn't scale either. We're constantly growing and I think we would hit the 100/s limit before Mojang would actually shut down the legacy API we're using at the moment.

The best we can do is encouraging users more to **not use names**.

I like the way [Visage](https://github.com/unascribed/Visage) (the Lapitar successor) does this:
> #### Don't look up by username!
Usernames are supported for testing **only**, and support may be dropped at any time.

> Since name changes are now possible, usernames are not a reliable way to look up a player's, well, anything. If you absolutely must look up by username, it's better to do this on your end and store the UUID in your database. This is more for your safety than ours.

> **Every time you request an avatar or anything else Minecraft-related by username instead of UUID, Notch and Dinnerbone kill a sheep. Save the sheeps!**

**Comment by Jake0oo0** [comment]
Can you hop on IRC @jomo?

**Comment by Jake0oo0** [comment]
Closed due to Mojang API restrictions. Crafatar already encourages that you use UUIDs when making requests, and you should continue doing so.
