### ISSUE TITLE
Support any userid as default

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#115]
A couple of websites seem to ~~misinterpret~~ not read our docs on the `default` parameter and use usernames instead of `alex` or `steve`.

This usually works because e.g. `/avatars/0?helm&size=64&default=jomo` will result in
```HTTP
HTTP/1.1 301 Moved Permanently
...
Location: jomo
```

I don't think this is proper use of the Location header, but browsers accept it as a relative path, causing a redirection to `/avatars/jomo`. Obviously the size or any other previous parameters are missing now.

-----

It would be a nice feature to allow this to work with any name. We have two ways to implement this:

0. Redirect to `/avatars/{default}?{params}`
0. No redirection, send image of `{default}` instead

And we should think about this:

0. What should we do when we can't get a skin for `{default}`? Just render the steve/alex as usual or should users be able to specify that as well (e.g. `default=jomo.alex`)
0. Both `steve` and `alex` are valid accounts, this would make it impossible to use these accounts as a fallback.

-----

However, it's already possible to do this without any issues (and including steve/alex) by just passing the full crafatar URL to the `default` parameter. Is it worth to implement this at all or should we just point this out in our docs?

**Comment by Jake0oo0** [comment]
Of course I can't spell, so Github didn't close the issue.

I implemented this via the first option, mostly because by the time that the request is already received and is sent to the correct route, we would have to create a workaround to redo the request, and this way we can easily redirect the request. All the params are kept, except for the default param, since we don't currently have any protection to make sure that the request doesn't result in an infinite loop. ```https://crafatar.com/avatars/dvdfvfd?default=Jake_0&helm``` will redirect to ```https://crafatar.com/avatars/jomo?helm```.

I haven't added tests yet, as I haven't completely looked them over yet, but we'll need to have some skins that we can rely on so that we can redirect to them for testing. Will look into that tomorrow.

**Comment by Jake0oo0** [comment]
@jomo ^

**Comment by jomo** [comment]
> https://crafatar.com/avatars/dvdfvfd?default=Jake_0&helm will redirect to https://crafatar.com/avatars/jomo?helm

I assume you meant `default=jomo` :stuck_out_tongue: 
The commit looks good, I'd like to keep this open so we don't forget about tests.

*btw: no need to mention me, I'm watching this repo :)*

**Comment by Jake0oo0** [comment]
That's what I get for even contemplating working on something after one in the morning :(

**Comment by Jake0oo0** [comment]
These CRC tests are really annoying :( I assume you have Canvas/something installed differently that results in a different CRC. Do you have a workaround for that to make them consistent? Travis also appears to be failing completely unrelated tests for some unknown reason...the inconsistencies between machines are a bit annoying.

**Comment by jomo** [comment]
It indeed is fairly annoying. I spent a lot of time trying to figure out what's causing it, but I never actually did. There are some details in https://github.com/crafatar/crafatar/issues/119#issuecomment-98552753 and 9f04fbc136b6c5b1ed79e2b20908de0953a1a132.

I **assume** it's coming from [Automattic/node-canvas](https://github.com/Automattic/node-canvas) or cairo.

I usually end up making a travis branch where I dump base64-encoded images and it's raw crc value to the log, let travis run over it, decode the base64 on my machine, confirm it looks okay and add the crc value in the master (or active) branch.

The changes in the travis branch would look like this:

```diff
-env: TRAVIS=true
+env: TRAVIS=true VERBOSE_TEST=true
```
```diff
             try {
               assert.ok(matches);
             } catch(e) {
+              console.log(body.toString("base64"));
               throw new Error(crc(body) + " != " + location.crc32);
             }
```



This sucks, so feel free to come up with any better solutions :)

**Comment by Jake0oo0** [comment]
Added redirect tests to a2e0edc4912e55bcf0150951a2aaacd947597830
