### ISSUE TITLE
Render tests failing on travis

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#119]
Via [#116](https://github.com/crafatar/crafatar/pull/116#issuecomment-96278683)

-----

Apparently renders are returning corrupted images, except sometimes™ when the `helm head render with not existing uuid defaulting to alex` test is the only one that passes.

This is only happening on travis. It works on my machine and also works on dokku.

As these errors only happen with renders, they must be coming from either node-canvas or Cairo.

[Here is](https://gist.githubusercontent.com/jomo/db54b4365879340b7efb/raw/968b71800cbfb1448edf17cfb9756c3fb2c4aa46/corrupted_utf8_png.base64) one of these corrupted images (as base64).

Usually, PNG images start with these 8 bytes `89 50 4e 47 0d 0a 1a 0a` (the [PNG Signature](http://www.w3.org/TR/PNG/#5PNG-file-signature))
The corrupted images, however, start with `ef bf bd 50 4e 47 0d 0a` for some reason.

I will try to find out more some time, but right now ~~I'm quite sure this is caused by Cairo.~~

**Comment by jomo** [comment]
Very similar issue with the same broken PNG signature: jembi/openhim-core-js#171.
When you google that sequence you'll [find](https://gist.github.com/proppy/573647) a [few more](https://stackoverflow.com/questions/8318314/linux-to-windows-bad-encoding-response) reports about it.

Looks like an encoding issue, apparently the binary data is encoded to UTF-8 somewhere™ which obviously doesn't work very well.

**Comment by jomo** [comment]
I was able to reproduce the corrupted binary issue:

```JavaScript
b = new Buffer([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
// <Buffer 89 50 4e 47 0d 0a 1a 0a>
new Buffer(b.toString());
// <Buffer ef bf bd 50 4e 47 0d 0a 1a 0a>
```

**Comment by jomo** [comment]
I was hoping this would be fixed in  6e41423 + b039e97 ([view diff](https://github.com/crafatar/crafatar/compare/2d1876b...b039e97)). That was another issue with encoding in our tests, which is now fixed, however.
The issue with renders / travis still exists.

**Comment by jomo** [comment]
So the two commits above mentioned fixed the issue with encoding / corrupted images.

Apparently this issue is related to #32.
I compared an image that failed to pass the crc check vs my local version of that image:

![compare gif](https://i.imgur.com/pvUNeXj.gif)

**Comment by Jake0oo0** [comment]
holy shit.

**Comment by jomo** [comment]
yeah it's quite weird. feel free to mess around with the travis-testing branch
