### ISSUE TITLE
Pocket Editions Skins

### ISSUE THREAD

**Issue by Jake0oo0** [crafatar/crafatar#122]
Mojang is adding customs skins to Minecraft: Pocket Edition, and _should_ be providing API support for them. We should probably add support for these at some point down the road. We'll need to figure out if these skins differ from Minecraft's skins, and the possibility that there is a different endpoint for them.

[Here](https://mojang.com/2015/05/pocket-edition-getting-skins-chicken-jockeys-more/)

**Comment by jomo** [comment]
Does the pocket edition use different accounts?
If not, I'd think they just use your account's skin.

**Comment by Jake0oo0** [comment]
I'm not really sure about that, as I don't have that version. Waiting to see if I can find out more about how accounts are connected.

**Comment by Jake0oo0** [comment]
Not sure about this right now...will look into whether or not it's actually relevant at some point when we have more info on the pocket edition skins.
