### ISSUE TITLE
Disallow additional slashes

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#123]
`https://crafatar.com/avatars/styles/whatever.css` is accepted as a valid request (showing the avatar for "styles").
IMO we should reject these requests.

**Comment by Jake0oo0** [comment]
How do you suppose we make this consistent @jomo? The case that you mentioned would be easy enough to filter out, but what if the last parameter in the request URL is the ```?default``` parameter, which could contain a slash? We would have to figure out how to prevent it from returning an invalid request if the URL was say ```https://crafatar.com/avatars?helm=true&default=google.com/logo.png```. The extra slash in the default param would cause it to be an invalid request...

**Comment by jomo** [comment]
A valid URL encoded parameter would look like ` https%3A%2F%2Fgoogle.com%2Flogo.png`.

Anyway, without looking at the code, I'm fairly sure we parse the URL, so we get path and params separated.

**Comment by jomo** [comment]
Also, the example you used actually *is* an invalid request because it has no userID :)

**Comment by Jake0oo0** [comment]
That still doesn't work in the case that the last parameter is the ```default``` param though, does it @jomo? Even if the URL is properly encoded, I don't know that we can ensure that there was not an extra slash after the default URL. Say in the example ```http://localhost:3000/avatars/Jake_0?default=twitter.com%2Fperson%2Favatar.png/style.css```. Looking at the ```path_list()``` code that you linked above, it doesn't seem to properly handle slashes after the main routes. In the same example, it only logs ```avatars``` and ```Jake_0``` in the path lis, even thought the URL is encoded, and there is the ```/style.css``` after the URL.

**Comment by jomo** [comment]
We should only care about additional slashes in the path, not in the parameters.

> I wonder if many of the default params that we receive are even properly URL encoded.

Probably not, but we have a misleading example on our website. Correctly encoded URLs are ugly and unreadable if you don't do this regularly, but we should consider fixing that.
It doesn't matter that much though. They should still be parsed correctly, unless these URLs have parameters, too, which would be parsed as parameters for crafatar and missing in the redirection URL.

**Comment by Jake0oo0** [comment]
Oh duh, there can't be anything after the parameters..otherwise that's just part of the parameter... Will look into that soon, been trying to setup new relic on a test heroku instance to figure out the issues with the latest master.

**Comment by Jake0oo0** [comment]
Reopened for addition of tests
