### ISSUE TITLE
Simplify website

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#126]
I believe the current website has too many technical details for the average user.
We should show an example for each endpoint, and only reveal the details (and maybe more examples) when you [expand that section](http://getbootstrap.com/javascript/#collapse-example-accordion).

**Comment by jomo** [comment]
We could also do some [SEO](# "Search Engine Optimization") while we're on it :)

**Comment by Tama63** [comment]
Hey @jomo sorry I've been away for a couple of months.

Bootstrap 4 is hitting soon - maybe we can recreate the site using this.

* Maybe using the inline code tag and tooltips to explain -> or use a table below.
* I agree
* Warning/danger notice?
* Maybe with the accordion plugin we can have "I'm a developer - tell me more" or "Additional developer..."

In terms of SEO tags + maybe reaching out to sites that use the service to include a link to boost the site's page rank.

**Comment by jomo** [comment]
I'd be okay with a *customized* bootstrap. IMO it looks very cheap otherwise, and I don't want the site to look like thousands of others.

> I'm a developer - tell me more

that's a good idea!

> reaching out to sites that use the service to include a link

Sounds great, we could also state on the website that we appreciate some kind of acknowledgment, like NameMC does:
![NameMC screenshot](https://i.imgur.com/ovk4MlD.png)

**Comment by Jake0oo0** [comment]
Maybe we could display a random group of sites from our [wiki](https://github.com/crafatar/crafatar/wiki/Who-uses-crafatar%3F)..

**Comment by Tama63** [comment]
@jomo perhaps with https://github.com/crafatar/crafatar/issues/132 we can sort out a colour scheme for the website relaunch.

**Comment by Tama63** [comment]
@crafatar/owners I'll take a crack at this after I've finished converting a website from PHP to meteor.

**Comment by jomo** [comment]
Great :+1:

**Comment by jomo** [comment]
@Tama63 do you think we could do it till 17 Oct? That would be Crafatar's birthday :gift:

Also, I like the current 'jumbotron' header, but we could shuffle the order of avatars with some JS on each visit.

**Comment by jomo** [comment]
I guess I'll have to get this done on my own _(unless @Tama63 awakens from the dead :stuck_out_tongue:)_
I'd also like to get rid of `jade`, and use something simple like [`bake`](https://github.com/pvorb/node-bake) instead. I don't think jade/HAML is particularly useful for us.

**Comment by jomo** [comment]
WIP pull request for this at  #150.

**Comment by jomo** [comment]
Fixed via #150.

**Comment by Tama63** [comment]
Sorry about the lack of reply, been really busy. Really like what you've done with the site :heart:
