### ISSUE TITLE
Transparent skins

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#129]
~~Should we carry over transparency in avatars & renders when the skin is transparent, or should we render them black (as they do in game)?~~

We should replace transparency with black (not the overlay though)

**Comment by TheDoctorsLife** [comment]
+1 for in-game like

**Comment by jomo** [comment]
Just to clarify, this is rendering transparent (what we currently do):
![transparent](https://i.imgur.com/k6NkiH1.png)
For renders, we could add the rear sides of the skin so it doesn't look weird.

And this is rendering game-like:
![game-like](https://i.imgur.com/dTDzEF8.png "this kinda looks like an optical illusion O_o")

----

I'm also +1 for game-like though.

**Comment by Gyzie** [comment]
Yeah I'm for game-like. It curently looks weird when showing a player list:
![knipsel](https://cloud.githubusercontent.com/assets/8080706/9831667/9de1e3e2-5960-11e5-9fb7-363a93f0cb20.PNG)
Same goes for head only of course.

**Comment by jomo** [comment]
Came across that exact page a few days ago and thought the image wasn't loading :P

**Comment by jomo** [comment]
@Gyzie have a look at #134. Transparent skins now render like this:
![transparent](https://i.imgur.com/AyQkm1Y.png)
Which is how they should appear in game.

**Comment by Gyzie** [comment]
@jomo Nice! Looks way better.

**Comment by jomo** [comment]
Both renders and avatars should now look exactly as they do in game. (i.e. transparent = black, translucent = opaque color)
