### ISSUE TITLE
Migrate Travis builds

### ISSUE THREAD

**Issue by Jake0oo0** [crafatar/crafatar#131]
Travis is moving away from their "legacy" builds and implemented a "better" build system. We use the old one.

[See here](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade#How-can-I-use-container-based-infrastructure%3F)

[Our legacy builds](https://travis-ci.org/crafatar/crafatar/builds/71898621)

**Comment by jomo** [comment]
@c2d2644bbe1cb6e70b7f695004c820b6b7a55d11 // [build 72196866](https://travis-ci.org/crafatar/crafatar/builds/72196866)

**Comment by jomo** [comment]
well the tests ran fast as :shit:
