### ISSUE TITLE
New Logo / Icon?

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#132]
I liked the way our current logo [was created](https://github.com/crafatar/crafatar/wiki/The-Logo) but I never really liked the logo itself.
It's too dark and just a generic face (_okay, that was the point_) and it's not even remotely remarkable or good-looking.

![screenshot](https://i.imgur.com/nGcebml.png)

Just my opinion, maybe others think otherwise, but I don't like it.
Should we find a new logo or at least lighten it up a little?

~~Maybe re-use the original idea and make it a gif? idk.~~
I'm particularly bad at creative ideas, so any feedback is welcome.

**Comment by TheDoctorsLife** [comment]
Why not a gif with a crafting table, & a steve/alex face?

**Comment by jomo** [comment]
Is this what you mean? Doesn't look that good imo :/
![crafting-alex-steve.gif](https://i.imgur.com/8nkDroY.gif)

**Comment by Jake0oo0** [comment]
I don't think a gif is a very good idea to be honest, it would take away from the more important info on the website, and a flashing logo is kinda annoying.

**Comment by jomo** [comment]
Yep I just noticed that as well.

**Comment by kylerschin** [comment]
pickaxe over command block?

**Comment by jomo** [comment]
@kylerchin thanks for the suggestion!

I went with a darkened 3d version of a command block and an enchanted diamond pickaxe in front of it. e69b3f38fb71cfea35eea870ccc63cbaaa2a2c6e

![logo](https://raw.githubusercontent.com/crafatar/crafatar/e69b3f38fb71cfea35eea870ccc63cbaaa2a2c6e/lib/public/logo.png)

In my opinion it's much better than the old logo :)
