### ISSUE TITLE
alex/steve shouldn't be used for default parameter

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#142]
[Quote](https://bugs.mojang.com/browse/WEB-12?focusedCommentId=234918&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-234918) from @krisjelbring:

> As far as I know Alex is just a regular account. There's no special handling around the name Alex. I'm not really sure if the Steve account is supposed to have a cape or not but it could potentially change in the future.

Also, the Alex account has no skin and its UUID (`ec561538f3fd461daff5086b22154bce`) actually defaults to a Steve skin.
We currently use `default=alex` and `default=steve` in our examples and have special handling for them.

As Kristoffer suggests, we should use `MHF_Alex` and `MHF_Steve` instead.
These two could be stored by us in place of the current Alex & Steve skins.

Breaking changes suck and we have a lot of people using the `default` parameter with `alex` or `steve`.
We should probably implement this without removing the existing special case and then deprecate the use of `alex`/`steve`.
### Note

This only affects the `default` parameter. Direct queries for Steve/Alex are no special cases.
If we implement this, I suggest not having any special cases for the `default` parameter at all and instead make them general special cases.
The only 'special case' would be that we don't query Mojang's server for `MHF_Alex` + `MHF_Steve` skins.

**Comment by jomo** [comment]
Legacy support could work by rewriting `default=alex/steve` to `default=mhf_alex/mhf_steve`.

**Comment by Minenash** [comment]
Haven't you fix this?

> default: The fallback to be used when the requested image cannot be served. You can use a custom URL or any uuid.
The option defaults to either MHF_Steve or MHF_Alex, depending on the requested UUID. All usernames default to MHF_Steve.
