### ISSUE TITLE
DNS caching

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#143]
Saw some errors like this on high load:

```
http://textures.minecraft.net/texture/123whatever
Error: getaddrinfo ENOTFOUND textures.minecraft.net textures.minecraft.net:80
    at errnoException (dns.js:25:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

We already do local DNS caching on our machine, so the issue is coming from somewhere else.
Someone described pretty much the same issue here: https://github.com/nodejs/node-v0.x-archive/issues/5488#issuecomment-17997237, it might be caused by ulimit, but others mention bugs on ubuntu as well.

Anyway, we should look into it and see if we can avoid it.
Perhaps using https://github.com/yahoo/dnscache, we only have a total of 3 domains to resolve anyway.

**Comment by kylerschin** [comment]
working on it.... could just be nodejs rejection error.

**Comment by jomo** [comment]
Didn't notice this error anymore recently. Was possibly caused by `net.nf_conntrack_max` being too low.
