### ISSUE TITLE
Skin Render Issue

### ISSUE THREAD

**Issue by jacobwgillespie** [crafatar/crafatar#152]
I seem to be having trouble getting one of my player's skins to show up correctly with Crafatar.

This is the skin in question: http://textures.minecraft.net/texture/b436ce322be9ab5f6446e128a7aebb24bd95a950b44ef6eb33ff3e3ab8675

In game, it renders as a user with a blue shirt and pants with black hair.  Here's an example (from [here](https://www.minecraftskinstealer.com/player.php?user=coolriderx1)), though interestingly the red "hat" doesn't show up in-game:

![skin](https://cloud.githubusercontent.com/assets/130874/11020847/14de1ff6-85f3-11e5-9c7b-94e966ac869c.png)

However, this is how Crafatar (and several other similar services) renders the skin:

![68c3c8470e7144978cc0ed2602aa3a29](https://cloud.githubusercontent.com/assets/130874/11020851/3a4f8f04-85f3-11e5-8dd9-6cbb9cb97c05.png)

The player's username is coolriderx1 and the UUID is 68c3c8470e7144978cc0ed2602aa3a29.  Any ideas what's going on here?  I can see the "skin" part in the original skin, but don't know enough about how things work to understand the discrepancy between game and Crafatar.

**Comment by jacobwgillespie** [comment]
Overlays?  First time I've heard of them!  Anyways, with `?overlay=true` the red hat returns, but still not the body:

![68c3c8470e7144978cc0ed2602aa3a29 1](https://cloud.githubusercontent.com/assets/130874/11020882/2aaf8d6e-85f4-11e5-8ab7-70999214cae5.png)

**Comment by jomo** [comment]
Currently renders only support the hat overlay, see #112. That is going to be fixed with #134.

*Closing as duplicate*

**Comment by jacobwgillespie** [comment]
Awesome, thanks!  :+1:
