### ISSUE TITLE
Current head renders look worse than what they used to look like

### ISSUE THREAD

**Issue by Brottweiler** [crafatar/crafatar#170]
A long time ago I downloaded a [Head Render](https://crafatar.com/#head-renders) of my skin, and I did it again today to see if they got an update and maybe looked different or better. They look different for sure.

Maybe this is just my opinion, but I have some points I think are valid to why I think like I think. 

This is the current Head Render

![image](https://cloud.githubusercontent.com/assets/1613137/14960476/1d170f16-1095-11e6-8ead-4e2f3814c0ba.png)

and this is the former (at one point) Head Render

![image](https://cloud.githubusercontent.com/assets/1613137/14960486/284e83aa-1095-11e6-94a9-5a2ef96466bd.png)

In my opinion, the old Head Render looks way better than the current one, for these reasons:

- It has a shadow (this should probably be optional anyway).
- It has shading; the right side of the head is darker than the top, and the front of the head is also slightly darker than the top.
- It may or may not be from a better angle.

Load up the images in two new tabs and cycle through them or something to see the differences. The new renders has no details, shading or shadow which the old ones have, and they look better with it rather than without.

**Comment by jomo** [comment]
We never had shading or shadows on our renders. We chose to return exactly the same color as defined in the skin file instead of tampering with it. Perhaps you got your render from a different site?

We left out shadows as well and left the option for users to apply (e.g. via CSS as done on our website).

I think we have an open feature request for "true" 3D renders with perspective / shading additional to isometric heads.

**Comment by Brottweiler** [comment]
I guess I can't really prove that it was from Crafatar, so maybe I am mistaken then, Thanks.

**Comment by jomo** [comment]
See #90, #154

**Comment by Brottweiler** [comment]
I just found out that the render I got was from Cravatar, not Crafatar... names so similar... Just though I'd update and add that.
