### ISSUE TITLE
Send content-length response header

### ISSUE THREAD

**Issue by turt2live** [crafatar/crafatar#238]
Currently the API does not send the Content-Length header, making some predictive memory usage a little harder. It would be nice if it sent the header so the consumer can accurately expect a size, and optionally do additional processing before dealing with the image.

**Comment by jomo** [comment]
IIRC the reason this wasn't implemented in the first place is that we didn't always use types with a known length, (e.g. #70 piping files to a [stream](https://nodejs.org/api/stream.html)). I think as of 69f0ee23be6eaf0fa860df45b92ae6108214d84b that shouldn't be an issue.

Should be an easy fix.
