### ISSUE TITLE
nickname support

### ISSUE THREAD

**Issue by SimonMeskens** [crafatar/crafatar#248]
Is there a reason why you guys aren't supporting nicknames anymore? There's a very simple Mojang API for getting the UUID from nickname at https://api.mojang.com/users/profiles/minecraft/Notch

**Comment by jomo** [comment]
Yes. As [noted on the website](https://crafatar.com/#meta-usernames), Mojang has [disabled](https://bugs.mojang.com/browse/WEB-985) the skin API for usernames. In fact, Mojang had already deprecated usernames before Crafatar was started and we always had a warning on the website that usernames may break and be disabled at any time.

We looked into using the API endpoint you mentioned, but unfortunately it is strictly rate limited, which in practice means we can't support it. See #106 for the details and discussion.

Spinning up a bunch of proxies to circumvent the rate limiting is out of the scope of this project.

----

If you want to use usernames, just do the conversion to UUIDs on your side and send UUIDs to Crafatar.
