### ISSUE TITLE
usernames

### ISSUE THREAD

**Issue by XInfiniterX** [crafatar/crafatar#249]
Please support usernames instead of uuid.
Minotar supports usernames, why crafatar does not?

**Comment by jredfox** [comment]
they could but, it would slow the process down a bit:
https://api.mojang.com/users/profiles/minecraft/username

then parse as json get uuid > then do default process
https://sessionserver.mojang.com/session/minecraft/profile/" + uuid + "?unsigned=false

**Comment by Jake0oo0** [comment]
Crafatar no longer supports usernames, and there are no plans to after Mojang officially "deprecated" them earlier this year by removing http://skins.minecraft.net.

**Comment by jomo** [comment]
See also #248
