### ISSUE TITLE
detect if user is alex or steve?

### ISSUE THREAD

**Issue by jredfox** [crafatar/crafatar#250]
detect if user is alex or steve? I used https://crafatar.com/skins/853c80ef3c3749fdaa49938b674adae6?default=MHF_Alex for a steve skin and it resulted in no 404 error.

The point of your site it for when mojang's cooldown isn't right you have to use your site the issue is the model of the player doesn't get stored anywhere and there is no model(steve/alex) section so confused.

I think you should have a json section where it tells you the user's name,uuid,model,cape everything about said player

**Comment by jomo** [comment]
The default model depends on the UUID. The function that calculates it can be found here: https://github.com/crafatar/crafatar/blob/1816b18b1292fca7ae123212b2b516a7532a332a/lib/skins.js#L137-L141

The model type of a player *is* stored, as can be seen here: https://github.com/crafatar/crafatar/blob/1816b18b1292fca7ae123212b2b516a7532a332a/lib/cache.js#L73-L74

Your text isn't very accurate and I don't really understand what you're trying to say. Are you reporting a bug? In that case, please specify steps to reproduce and the expected vs. actual outcome.

**Comment by jredfox** [comment]
parseInt() without showing a method and using index array rather then showing how to get that array that doesn't help me.

Also players can change their model with a skin change your telling me their uuid changes each time I think not

**Comment by jomo** [comment]
The *default skin* (Alex/Steve) is based on the UUID. The model type used by a player is returned by the Mojang API and retrieved here: https://github.com/crafatar/crafatar/blob/1816b18b1292fca7ae123212b2b516a7532a332a/lib/networking.js#L102

I'm still not sure what you're asking for or trying to do. Can you please specify?

**Comment by jredfox** [comment]
that's if and only if they don't set their model and skin

**Comment by jomo** [comment]
I'm still not sure what you're asking for or trying to do. Can you please specify?

**Comment by jredfox** [comment]
I want the entire skin data info to be cached from craftar but, your api doesn't provide enough info:
https://bugs.mojang.com/secure/attachment/133164/Skin%20Issue.png

issues:
alex isn't detectable since there is no crafatar.com/uuid.json 
alex model can be set on skin so saying it's based on uuid is not accurate if the user has an actual skin
the only way to test if player has cape is to do the whole url connect process which takes up to a whole second rather then just having a json file per player that I can see what all the data is.

What craftar needs to become a replacement for mojnang api:
https://pastebin.com/Fsgd71VA

**Comment by jomo** [comment]
I see. Feel free to submit a PR for something like `/info/<uuid>.json` that exposes our cached information (after fetching it from Mojang, if necessary).

**Comment by jredfox** [comment]
in issues or where?

**Comment by jomo** [comment]
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by jredfox** [comment]
yeah I don't code html but,you people can
