### ISSUE TITLE
You can't just restore skins from nicknames with that?

### ISSUE THREAD

**Issue by js6pak** [crafatar/crafatar#252]
http://wiki.vg/Mojang_API#Username_-.3E_UUID_at_time

**Comment by js6pak** [comment]
Hmm, what limit? On wiki.vg i only see limit of NAMES in ONE request.

**Comment by jomo** [comment]
The first part on the wiki.vg page:
> All public APIs are rate limited so you are expected to cache the results. This is currently set at 600 requests per 10 minutes but this may change.

See also discussion in #106.

**Comment by LukeHandle** [comment]
Following from @jomo popping into https://github.com/minotar/imgd/issues/158#issuecomment-161003826 (and me finalling closing that issue), and following through into https://github.com/crafatar/crafatar/issues/106 and now here -

A much less looked after skin site, [Minotar](https://minotar.net/), still (for a very short time longer :laughing: , _only_) supports Username lookups via caching it to a UUID. The UUID can then be requested from Mojang which conveniently contains the Username which we can confirm is thus cached correctly.

eg. Store Username -> UUID for X days (long TTL). Store UUID -> User Data/Skin ID etc. When a username request comes in, we optimistically check caches, then if the UUID->UserData cache is older than X, we re-check the UUID against Mojang (to ensure we have up to date Skin info, and Username is still the same).
If that UUID is tied to a different username, we cache what we got so far, then go back and request the Username from Mojang as per normal and continue.

1G will store ~6.5M usernames -> UUID. The UUID -> UserData is obviously more expensive to cache, but less rate limited. Thus, if the skin is requested "fairly often", depending on your Username cache size, it will rarely need a request to Mojangs Username API. It does unfortunately mean the Username cache becomes more valuable/painful upon clearing.

_The other trick is spreading the API requests across as many IPs as possible_

**Comment by jomo** [comment]
Thanks for following up! That's a very smart way to reduce the API calls, but from my understanding unfortunately doesn't scale and won't entirely solve the issue. All it takes is 600 name requests that haven't been cached yet and the (username part of the) service is DoSed for the next 10 minutes.

We currently have tens of thousands of uncached UUID requests per 10 minutes, so it's safe to assume we'd likely get more than 600 uncached username requests :/
