### ISSUE TITLE
.png URL have wrong/old skin

### ISSUE THREAD

**Issue by DiogoSaraiva** [crafatar/crafatar#266]
Hi,
I changed my skin at mojang, but it is not syncing with crafatar correctly, when I got to https://crafatar.com/skins/707cc485e60c48be9e5ccdfae999f8b0.png it show old skin, but when i go to https://crafatar.com/skins/707cc485e60c48be9e5ccdfae999f8b0 it shows the correct one.

**Comment by jomo** [comment]
This is due to caching of your browser and/or Cloudflare. You can try clearing your browser cache after changing your skin, but it's expected that it may take a little while until you see the change. 

See also [About caching](https://crafatar.com/#meta-caching).
