### ISSUE TITLE
New 3D Render type

### ISSUE THREAD

**Issue by Nisutec** [crafatar/crafatar#267]
Hallo,
Is it at the moment possible to create a more 3D render with crafatar like this render. At the moment the body render is very nice but is it possible to make the Skin more 3D like this.

![3D Render](https://p52.p0.n0.cdn.getcloudapp.com/items/4guy0Rkl/render.png?v=fe6fc6d5f68c875a847ff718b9119f9c)

**Comment by jomo** [comment]
Take a look at @InventivetalentDev's [MineRender](https://github.com/InventivetalentDev/MineRender). It uses skins from crafatar to create 3D renders like the one you posted.
