### ISSUE TITLE
Get permanent steve render?

### ISSUE THREAD

**Issue by Beatso1** [crafatar/crafatar#270]
Is there currently a way to get a head render that is guaranteed to be a steve head?

**Comment by jomo** [comment]
Yes. You can use the `MHF_Steve` account (UUID `c06f8906-4c8a-4911-9c29-ea1dbd1aab82`).

**Comment by ajs256** [comment]
@Beatso1 - Mojang has quite a few accounts for which the skin will never change, you can see the list [here](https://minecraft.gamepedia.com/Head#Mojang_Studios_skins).
