### ISSUE TITLE
Use better status API

### ISSUE THREAD

**Issue by ajs256** [crafatar/crafatar#272]
[Mojang's status API](status.mojang.com/check) has not been updated in months and shows red when everything works fine. [mc-heads.net's Mojang status page](https://mc-heads.net/json/mc_status) updates, but the JSON is in a different format. Can someone change the code in [`/lib/public/javascript/crafatar.js`](https://github.com/crafatar/crafatar/blob/master/lib/public/javascript/crafatar.js) to use this API?

More discussion is in #271.

**Comment by MisterFixx** [comment]
#273
