### ISSUE TITLE
Alex skin rendering?

### ISSUE THREAD

**Issue by DrDeee** [crafatar/crafatar#278]
Can Crafatar also do Alex skins or only Steve skins?

**Comment by jengel3** [comment]
You can specify the default skin with the `default` query parameter: 

e.g: [https://crafatar.com/avatars/853c80ef3c3749fdaa49938b674adae5?default=MHF_Alex](https://crafatar.com/avatars/853c80ef3c3749fdaa49938b674adae5?default=MHF_Alex)

Valid options are `MHF_Alex` and `MHF_Steve`

**Comment by jomo** [comment]
If you want to get alex or steve specifically, you can use the UUIDs

- `6ab4317889fd490597f60f67d9d76fd9` (for `MHF_Alex`)
- `c06f89064c8a49119c29ea1dbd1aab82` (for `MHF_Steve`)

**Comment by MisterFixx** [comment]
I think @DrDeee is asking whether crafatar can render slim model skins

**Comment by DrDeee** [comment]
Yes, that was my question, @MisterFixx

**Comment by jomo** [comment]
That has been implemented 5 years ago, see #125.

**Comment by DrDeee** [comment]
Thanks for the realy fast response!
