### ISSUE TITLE
Outer layer not rendering 

### ISSUE THREAD

**Issue by Squirrelcoding** [crafatar/crafatar#286]
This really isn't a big deal but it still bother's me that outer layers of Minecraft skins aren't rendering. I cant provide much details since the title is really straightforward but here's an example:

### normal technoblade (nameMC)
![a](https://i.ibb.co/VjGK0b2/image.png)
### Crafatar Technoblade (below)
![b876ec32-e396-476b-a115-8438d83c67d4](http://crafatar.com/renders/body/b876ec32-e396-476b-a115-8438d83c67d4)
he small

**Comment by jomo** [comment]
> outer layers of Minecraft skins aren't rendering

use the `overlay` parameter, as documented on crafatar.com.

> he small

use the `scale` parameter, as documented on crafatar.com.

---

[![b876ec32-e396-476b-a115-8438d83c67d4](http://crafatar.com/renders/body/b876ec32-e396-476b-a115-8438d83c67d4?scale=10&overlay)](http://crafatar.com/renders/body/b876ec32-e396-476b-a115-8438d83c67d4?scale=10&overlay)
