### ISSUE TITLE
Support for GeyserMC Skin API (Bedrock Edition)

### ISSUE THREAD

**Issue by Tydium** [crafatar/crafatar#287]
I think if you guys added support for GeyserMC/Bedrock edition skins that would be incredibly pog. I have a way of getting the skins from bedrock edition, but I don't know how to render it myself through crafatar which is what I am trying to figure out. 

**To get Geyser/Bedrock Edition skins**
Step 1: Using their api "https://api.geysermc.org/v1/skin/*xuid*" you can grab the texture id. (Example Link: https://api.geysermc.org/v1/skin/2535449110338826)
Note: Their api spits out some more info, and the "Texture id" is in the middle of it. (Here is an example id: "texture_id":"91ccdfb82d691076415bdac4d727046d2b6c047399ce86bc9dff3842c3e6e4ef")

Step 2: take the ID from the geyser api and put it into http://textures.minecraft.net/texture/*ID*
(Example: http://textures.minecraft.net/texture/91ccdfb82d691076415bdac4d727046d2b6c047399ce86bc9dff3842c3e6e4ef)

From there you could see the bedrock player skin.
![image](https://user-images.githubusercontent.com/67938521/117556392-6e4a0780-b036-11eb-8601-c94f66805098.png)

There's a lot more people needing this now more than ever. If this was part of crafatar that would be extremely helpful for a lot of server owners/devs. (Approximately 12000 servers with geyser.) . Best luck to you if you attempt to try to add this to the crafatar API. If you want their discord to ask the devs questions or if you need something from them please feel free to ask. Good luck!

**Comment by jomo** [comment]
This is basically the same feature request as #54. I'll close this as a duplicate so we can track the feature there.
