### ISSUE TITLE
Is Crafatar down? 

### ISSUE THREAD

**Issue by bmxmikey** [crafatar/crafatar#292]
On the site I'm working on currently none of the avatars are showing up properly and I'm getting a 500 ERROR code for the avatars, I checked my code and manually inserted the URL into google plus used Minecraft UUID / Username search and all give me Alex/Steve skins. If this is an issue is there a known reason why? Thank you in advance for responses!

Edit: also forgot to mention that even the Avatars on the site are Steve/Alex besides one.
![Crafatar Home Page](https://user-images.githubusercontent.com/44886996/126887877-c00ca220-1bb9-4856-8765-e9e610974260.png)

**Comment by jomo** [comment]
Something hung up, should be fixed now.
