### ISSUE TITLE
Dinnerbone/Grumm renders are not flipped

### ISSUE THREAD

**Issue by ChloeDawn** [crafatar/crafatar#293]
When requesting a body/head/avatar render of Dinnerbone or Grumm, the resulting image is not flipped. This behaviour conflicts with the examples on the website showing upsidedown avatars.

**Comment by jomo** [comment]
Crafatar returns the skins exactly as the Mojang API does.

If you want some special handling (such as shown on the website) you can do it just like the website does: https://github.com/crafatar/crafatar/search?q=flipped&type=code

**Comment by ChloeDawn** [comment]
A model render flip would require more than flipping the flat image in CSS. Would it be possible to get some sort of flag added to the API, in a similar vein to https://github.com/crafatar/crafatar/issues/253?
