### ISSUE TITLE
Add an endpoint for converting texture url to isometric cube

### ISSUE THREAD

**Issue by UP929312** [crafatar/crafatar#294]
When base64 decoding a skull's texture string, you get out a texture url, which looks like this:
http://textures.minecraft.net/texture/9336d7cc95cbf6689f5e8c954294ec8d1efc494a4031325bb427bc81d56a484d
Would you be able to add an endpoint which takes the data after texture and returns an isometric cube, exactly like 
https://crafatar.com/renders/head/uuid does? Just instead of uuid, it takes the texture's id of
9336d7cc95cbf6689f5e8c954294ec8d1efc494a4031325bb427bc81d56a484d

**Comment by jomo** [comment]
#54
