### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by IzMichael** [crafatar/crafatar#297]
I've been using the api for a few days now, and it's suddenly stopped working? The website header confirms this.
![image](https://user-images.githubusercontent.com/57115702/131314378-2c1c99a6-1b90-4aef-abdd-10e2fee7d754.png)

`https://crafatar.com/renders/body/d149273e-2580-4881-9b59-bf7213ec72bb.png` just returns Alex
![image](https://user-images.githubusercontent.com/57115702/131314635-a6d16f17-cc13-421f-b2e6-ea6d05c7224d.png)

**Comment by jomo** [comment]
Thanks for the report.
Sometimes there are small issues that usually go away on their own after a few minutes.

In this case, it looks like it's already fixed.
