### ISSUE TITLE
Skin stays black

### ISSUE THREAD

**Issue by xBengie** [crafatar/crafatar#306]
83bf8c8d94634abc829ef6f545b2dc80

My skin stays black :( 

Can you please fix this?

**Comment by jomo** [comment]
I'm fairly sure you've made your skin transparent, which isn't supported by Minecraft and thus just renders the RGB value of the pixels (black in this case). The overlay layer seems to fully contain a skin, which is rendered by crafatar with the `overlay` layer.

tl;dr your skin is black, so it's rendered black.
