### ISSUE TITLE
there are errors in the layer

### ISSUE THREAD

**Issue by huanmeng-qwq** [crafatar/crafatar#310]
![image](https://user-images.githubusercontent.com/49704373/215852256-8b3e45b1-0d11-4109-9b1c-bf1afc7a4fc8.png)
this is what I saw in the skin editing tool

but...
The image layer I obtained using the api is inside, not outside
https://crafatar.com/renders/body/83889e3db79e45d094afa88d2b87a44e?overlay
![83889e3db79e45d094afa88d2b87a44e](https://user-images.githubusercontent.com/49704373/215852946-4a7bea39-1536-422a-9ad2-3442a5551788.png)

uuid: 83889e3db79e45d094afa88d2b87a44e

**Comment by jomo** [comment]
crafatar never supported the exploded rendering of the overlay and I don't currently plan to continue development, sorry.
I might consider PRs to address this, though.
