### ISSUE TITLE
crafatar.com leads to Heroku "There's nothing here, yet." page

### ISSUE THREAD

**Issue by Tisawesomeness** [crafatar/crafatar#314]
Issue seems identical to #312.

![image](https://github.com/crafatar/crafatar/assets/17386338/8cdd2135-e9f9-4190-a1ed-1eee26fa9960)

**Comment by ToxicStoxm** [comment]
I think they shut down i didn't find any information either

**Comment by sauramel** [comment]
I'm looking at putting this up on our own site asap, I will report back soon

**Comment by jomo** [comment]
Everything should be back to normal, thanks for the report.

**Comment by Micaxs** [comment]
> Everything should be back to normal, thanks for the report.

seems this is the case again, sorry for bumping old thread, figured easier then to open a new issue.

**Comment by SamLeGgamer** [comment]
Same for me

**Comment by sauramel** [comment]
This is happening monthly

**Comment by jomo** [comment]
was a temporary issue that seems to have fixed itself again
