### ISSUE TITLE
Add Steve and Alex skins

### ISSUE THREAD

**Issue by gabrielmar** [crafatar/crafatar#319]
I can't get the default skins without passing an invalid UUID
Even passing this uuid 00000000000000000000000000000000, I am redirected to github
Maybe if you pass the name of the skins in the UUID value: MHF_Steve MHF_Alex

**Comment by jomo** [comment]
You're not supposed to use invalid UUIDs. You can use the actual UUIDs of the users `MHF_Steve` and `MHF_Alex` if you want their skin, just as you do with any other user's skin.
