### ISSUE TITLE
Fix 3D rendering glitches

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#32]
For some reason there is a tiny difference to the images, although the helm is empty (at these parts):

```bash
# `compare` comes with ImageMagick
compare \
  "477be35554684c28bdeee4cf11c591d3c88afb77e0b98da893fd7bc318c65184-6-body.png" \
  "477be35554684c28bdeee4cf11c591d3c88afb77e0b98da893fd7bc318c65184-6-bodyhelm.png" \
  "diff.png"
```
The difference is highlighted in red:  
![image diff](https://i.imgur.com/SWJM78J.png)

The two lines on the chin and cheek don't seem to resize on [larger images](https://i.imgur.com/Nfw2Mzu.png) though.

**Comment by jomo** [comment]
There is more discussion in #26. At the moment it seems to be a bug with Cairo.

**Comment by jomo** [comment]
IIRC we cut out, rotate, and transform images with a single canvas function call.
I wonder if it makes a difference if we split that into a few functions to cut out the different parts of the skin (as we do with avatars) and then pass them to Cairo for rotation etc.

Maybe that fixes those weird renders. maybe. these glitches are really annoying

**Comment by Jake0oo0** [comment]
Just ignore this for now, I want to redo the renders in the future and make them look better, really simple atm.

**Comment by jomo** [comment]
Maybe we could also try to reimplement this using WebGL (if we find that for node).

Just throwing in my ideas here...

**Comment by Jake0oo0** [comment]
Was planning on doing that, considering how bad the renders look with all the issues :stuck_out_tongue:
