### ISSUE TITLE
Down again

### ISSUE THREAD

**Issue by sauramel** [crafatar/crafatar#320]
Opening craftatar just leads to a "Theres nothing here" page

**Comment by illuminator3** [comment]
still just giving 521

**Comment by LeonBisai** [comment]
same

**Comment by jomo** [comment]
I'm sorry, but shit like this keeps happening :(

![image](https://github.com/crafatar/crafatar/assets/3585743/df32f784-d899-492f-bd08-c3b3f17b36b3)

Some people are just abusing the service again and again. I'll look into it.

**Comment by jomo** [comment]
I've made some changes, should be up again

**Comment by sauramel** [comment]
No dice

**Comment by jomo** [comment]
I've blocked some abusive requests that were causing high load on crafatar.com, the service is now up again.

**Comment by sauramel** [comment]
Pretty sure some of those requests/addresses you are blocking are important
to the discord client because I can now view the site on my browser but no
images from craftatar whatsoever will load on discord

**Comment by jomo** [comment]
Could you open a new issue with some details, e.g. which bot (or whatever source) these images come from, and as many technical details as possible? I don't use Discord so I can't debug this myself.

**Comment by purejosh** [comment]
I can attest to this. Discord's API is definitely having some issues with this. All of the sudden, heads stopped loading with discord sync'd messages. There's a plugin called EssentialsDiscord which I've put the craftatar URL link into, and it worked great until a month or so ago.
