### ISSUE TITLE
Problem with CORS

### ISSUE THREAD

**Issue by Tobias-Auer** [crafatar/crafatar#321]
Hi, I have a small website that uses the Crafatar service. About a week ago, everything worked just fine. However, as I opened my website today, the images from Crafatar didn't load. Initially, I thought Crafatar might be down again, but upon checking the server console, I noticed it wasn't a 404 or anything, but rather a 403 error.

Here's my error message:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://crafatar.com/avatars/4ebe5f6fc23143159d60097c48cc6d30?default=MHF_Steve&overlay. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 403`

I've done a bit of googling, but I haven't found a good solution. I don't want to use a proxy or anything like that.

It was working last week, and now it doesn't. I'm not that experienced with stuff like this xD.

A little help would be appreciated.

**Comment by jomo** [comment]
Sorry about that, I had to temporarily block requests on Cloudflare. It should be working again, please let me know if it doesn't.
