### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by James-Bennett-295** [crafatar/crafatar#323]
Hi, can you please enable Github's private vulnerability reporting so I can report something i've found? [Instructions here](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository#enabling-or-disabling-private-vulnerability-reporting-for-a-repository), thanks.

**Comment by jomo** [comment]
Hey, I have enabled private reporting now.

**Comment by James-Bennett-295** [comment]
I have created the report.

**Comment by James-Bennett-295** [comment]
@jomo I had submitted a report which was still there when I checked a few days later, but somehow wasn't there when I checked now. I've created another so let me know if you can see this.
