### ISSUE TITLE
Who uses Crafatar?

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#43]
[Moved](https://github.com/crafatar/crafatar/wiki/Who-uses-crafatar%3F) to a wiki page, containing:

* Websites using Crafatar
* Services & Plugins using Crafatar
* What people say about Crafatar

Feel free to contribute everyone!

**Comment by Nosxxx** [comment]
We also switched form Minotar ;) 
https://youcancraft.de/

**Comment by jomo** [comment]
Thanks for lettings us know

**Comment by rileriscool** [comment]
I use Crafatar on my skin/head/body download page:
http://rileriscool.playat.ch/renders.php

**Comment by Jake0oo0** [comment]
:+1:

**Comment by rileriscool** [comment]
I was lazy last night :P Fixing the HTML now

**Comment by confuser** [comment]
Considering using this service in the next BanManagement release (ban web interface for BanManager)

Would you be able to handle the influx in traffic? I don't have visibility on web usage, only on the plugin side which is currently a couple of thousand servers.

**Comment by jomo** [comment]
We didn't have any issues when technic used crafatar, so I'm sure we can handle the traffic :)
Thanks for informing us!

**Comment by Twister915** [comment]
http://arkhamnetwork.org will likely be using this in an upcoming minigame release :)

**Comment by Jake0oo0** [comment]
<3

**Comment by nerdtron123** [comment]
http://enduniverse.com is using this! Minotar loses another person!

**Comment by clone1018** [comment]
Ouch.

**Comment by jomo** [comment]
lol

**Comment by Tama63** [comment]
@crafatar/owners how about moving this issue to a wiki page, then linking said page in the README?

**Comment by jomo** [comment]
Great idea!

**Comment by Tama63** [comment]
@jom https://github.com/crafatar/crafatar/wiki/Who-uses-crafatar%3F if you want to copy over the contents of your op on this issue?

**Comment by jomo** [comment]
[Moved](https://github.com/crafatar/crafatar/wiki/Who-uses-crafatar%3F) everything, worked on the markup and added `What people say about Crafatar`.

**Comment by jomo** [comment]
## Please add projects using Crafatar to [the wiki page](https://github.com/crafatar/crafatar/wiki/Who-uses-crafatar%3F).
