### ISSUE TITLE
Extract response logic to new module

### ISSUE THREAD

**Issue by Jake0oo0** [crafatar/crafatar#45]
We currently have a lot of duplicate code. Extracting that to a new module wouldn't be a bad idea:

Examples:
https://github.com/Jake0oo0/crafatar/blob/master/routes/avatars.js#L17
https://github.com/Jake0oo0/crafatar/blob/master/routes/skins.js#L10

**Comment by jomo** [comment]
When #116 is merged we should have a look at this:

* is #66 fixed (or improved)?
* is #102 fixed?
* is #105 fixed?
