### ISSUE TITLE
Status Page

### ISSUE THREAD

**Issue by Jake0oo0** [crafatar/crafatar#53]

**Comment by jomo** [comment]
do you have any further thoughts on this? What exactly should it display?

**Comment by Jake0oo0** [comment]
Just current stats of the application. 

* Redis key count
* Uptime
* Json?
* Any other ideas?

**Comment by jomo** [comment]
What does JSON mean in this case?

-----

Would be nice to see a graph with percentage of different HTTP status codes, so if you [suddenly see a lot of 422](https://github.com/Jake0oo0/crafatar/issues/64) you could quickly see that something is probably wrong.
Same for the response time.

Maybe something like https://status.github.com/

**Comment by Jake0oo0** [comment]
I'll do this when I get home. I was talking about making it Json formatted. I'll add a bunch of the Info from redis info.

**Comment by jomo** [comment]
Found this, readme seems interesting: https://github.com/EverythingMe/redash

**Comment by Jake0oo0** [comment]
Looks interesting, not sure if we need something that complex though. Does it support redis?

**Comment by jomo** [comment]
May be too complex indeed, just saw that thing while browsing with my phone.

What we would need is something that queries logs every so often, caching the results and shows fancy graphs for those queries. We probably want to see the total # of requests, 200s, 404s, 503s for each image "type" (avatar/skin/body) and helm (y/n), average response time, number of redis keys, etc.

**Comment by Tama63** [comment]
@jomo https://happyapps.io/ just got released if you want to take another look at this issue?

**Comment by Jake0oo0** [comment]
Can't seem to connect to that site @Tama63

**Comment by Tama63** [comment]
@Jake0oo0 missed out the www. sorry: http://www.happyapps.io/#
