### ISSUE TITLE
CMS Plugins

### ISSUE THREAD

**Issue by Jake0oo0** [crafatar/crafatar#55]
[See](https://www.reddit.com/r/admincraft/comments/2r1xdr/using_skins_as_avatars_on_wordpress_site/) 

Creating plugins for various services wouldn't be a bad idea, and would help a LOT.

I'd suggest Wordpress and XenForo to start.

Time to learn PHP again :cry:

**Comment by jomo** [comment]
I found [this french website](http://excalicube.net/) and was wondering how the sidebar with online users was done.
Asked the admin and he told me they're using [minecraft-onlineusers-widget](https://wordpress.org/plugins/minecraft-onlineusers-widget/screenshots/) with modified code.

There's a [GitHub mirror](https://github.com/dasilvaj4/minecraft-onlineusers-widget/blob/master/widget.php) of the plugin, it seems to be pretty much hardcoded, including the author's server domain. Shouldn't be hard to fork & modify though.

**Comment by Tama63** [comment]
Had a quick crack it a while back for http://vanillaforums.org https://github.com/Tama63/vanilla-crafatar

**Comment by jomo** [comment]
nice

**Comment by jomo** [comment]
FTR this is now forked here: [crafatar/vanilla-forums-crafatar](https://github.com/crafatar/vanilla-forums-crafatar)

**Comment by rileriscool** [comment]
I may take a shot at a WordPress plugin for Crafatar.
What would you want the plugin to do?

**Comment by jomo** [comment]
The most common use case is to set users' (default) avatar to their MC face

**Comment by rileriscool** [comment]
Ok, So like an add on to the forum plugin?

**Comment by jomo** [comment]
Something like the gravatar plugin, except using crafatar :)

**Comment by rileriscool** [comment]
:) :+1:

**Comment by Jake0oo0** [comment]
Sounds good :+1: Haven't had much time to look into this, so I'm not really sure what functionality would be popular.

**Comment by jomo** [comment]
it's also very common to have a list of donators, bans, online players, or the like. However that could (*read: should*) be combined with their website account so the website avatar would be used there.
When their website avatar uses crafatar, their MC face would appear everywhere there.

**Comment by jomo** [comment]
Closing this as there are a couple of plugins listed at #43 already.
