### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#66]
Heroku keeps complaining about memory usage.

* https://github.com/felixge/node-memory-leak-tutorial
* https://hacks.mozilla.org/2012/11/tracking-down-memory-leaks-in-node-js-a-node-js-holiday-season/
* https://medium.com/@Philmod/debugging-node-js-29b2097df36c
* https://developer.chrome.com/devtools/docs/heap-profiling

**Comment by jomo** [comment]
So I found this:

```bash
sudo sysctl kernel/kptr_restrict=0
npm install -g stackvis
node --perf-basic-prof bin/www.js > logs/out.log &
 [1] 12345
perf record -F 99 -p 12345 -g -- sleep 30
perf script > perf.out
stackvis perf flamegraph-svg < perf.out > perf.svg
```

* `-F` adjusts defines frequency (Hz) and can be set much higher if needed.

This gives us some [nice flame graphs](http://www.brendangregg.com/blog/2014-09-17/node-flame-graphs-on-linux.html) for a period of 30 seconds.

We should try this with different versions of crafatar:

0. while idling
0. with a few requests
0. under heavy load.

Maybe that gives us an idea on what's wrong.

**Comment by Jake0oo0** [comment]
Aha! This is what I was looking for when Netflix released their blog post on memory issues with node a few months ago. Will try this sometime soon.

**Comment by connor4312** [comment]
Glancing at your code, you're throwing closures around everywhere. It seems likely that at some point(s) in you're app, you're maintaining a reference to one or more of these closures. When that happens, the _entire scope_ the closure belongs to is retained in memory.

Flame graphs are for CPU usages. You want to grab some [heap snapshots](https://github.com/bnoordhuis/node-heapdump), which should help you diagnose where your memory issues are coming from.

**Comment by jomo** [comment]
thanks for your tips @connor4312! will give that a try

**Comment by jomo** [comment]
Hmm, according to Douglas Crockford closures [are not](http://javascript.crockford.com/memory/leak.html) the cause of memory leaks:
> Since IE is unable to do its job and reclaim the cycles, it falls on us to do it. If we explicitly break the cycles, then IE will be able to reclaim the memory. According to Microsoft, closures are the cause of memory leaks. This is of course deeply wrong, but it leads to Microsoft giving very bad advice to programmers on how to cope with Microsoft's bugs.

our code definitely needs some cleanup though

**Comment by connor4312** [comment]
Closures definitely can be the cause of memory leaks if used incorrectly. The Crockford article you linked contains information about leaks fairly specific to IE6, and was not referencing closures at all. The landscape has changed much since IE6, and Node.js (V8) is an entirely different engine than that which powers Internet Explorer.

**Comment by jomo** [comment]
I'm not really familiar with this kind of stuff, but I hope it makes some sense:
![heap snapshots screenshot](https://i.imgur.com/rL89heP.png)

I used `setInterval` to write a heap snapshot every 60 seconds and [forwarded](https://gist.github.com/jomo/6d93132f98dfd6110dc1) traffic from production to my local server.
Snapshots taken while forwarding traffic are highlighted in black.

I sometimes waited a minute or two, snapshots taken during this time are highlighted in green.

Comparing two sequential idling-snapshots was usually a few new objects and the same amount of deleted objects, i.e. 0 new bytes.

In the end I compared the first of those idling snapshots with the last one. As you can see, there's about 0.2 MB of new objects that must have been added during requests.

Take a look at the size of the snashots on the lef and you can see that when idling after a bunch of requests, it cleaned up most of it, but not all of it and thus size is growing.

I also ran node with the `--expose_gc` flag and used `global.gc()` immediately before taking the snapshots so it wouldn't contain some stuff that'd be collected later anyway.

-----

Unfortunately I can't make much sense of the results and I couldn't really figure out where it might be coming from. Any ideas?

**Comment by connor4312** [comment]
Could you post the first and last heap snapshots here?

**Comment by jomo** [comment]
http://chunk.io/f/c0625c83754b45b08b99c044bcd55236

**Comment by jomo** [comment]
Just tried again after merging #116 – doesn't seem like it has gotten any better.

**Comment by jomo** [comment]
The current version doesn't show any signs of memory leaks.
Memory usage sometimes goes up on high load, but it goes down again when the load decreases.
