### ISSUE TITLE
Wait for cache writing callback

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#86]
ATM we initiate a write call to redis and then let that complete in the background.
Waiting for the completion callback might slow things down a tiny bit but it will help against errors on simultaneous requests for the same userid

**Comment by Jake0oo0** [comment]
How would it help with that issue?

**Comment by jomo** [comment]
Let's say we get 2 requests at (nearly) the same time. This is what could happen without this fix:

* Req 1 checks cache: userid not stored
* Req 2 gets queued
* Req 1 downloads image
* Req 1 starts writing to cache (we don't wait for completion)
* Req 1 done
* Req 2 checks: cache: userid not stored (writing not completed)
* Req 2 downloads image / hits rate limit
* Req 2 writes null hash to cache
