### ISSUE TITLE
nodejs v0.12 vs io.js

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#89]
So nodejs 0.12 has been released with changes to buffers and clusters.

There is also io.js made by a couple of former nodejs contributors, it would be worth comparing the two (speed/memory usage).

**Comment by Jake0oo0** [comment]
Looking into it.

**Comment by Jake0oo0** [comment]
lwip is definitely incompatible with 0.12.0, will see if I can fix that.

**Comment by Jake0oo0** [comment]
Seems that the changes to C modules in node.js have definitely broken something. Crafatar exits with the error code ```3221226356``` after a few requests.

**Comment by jomo** [comment]
`npm rebuild` does the trick

**Comment by jomo** [comment]
The lastest version of [n](https://github.com/tj/n) has support for iojs.
Can be installed via `npm install -g tj/n && n io latest`.

Seems to be working and all tests are passing, sadly travis doesn't have iojs yet, see travis-ci/travis-ci#3108.

We should run some benchmarks and decide check if io is faster and then switch if that's the case.
heroku / the nodejs buildpack has [support for iojs](https://github.com/heroku/heroku-buildpack-nodejs/pull/181).

**Comment by jomo** [comment]
I've benchmarked with node v0.12 and iojs v1.2. Average request time:
```Benchmark
not cached:
iojs v1.2:   1.06s
node v0.12:  1.09s

cached:
iojs v1.2:   0.00828s
node v0.12:  0.01005s
```

the non-cached once are network based, so we can't say for sure that iojs is faster, but the cached ones should pretty much proof it.
