### ISSUE TITLE
Support for 3rd party skins

### ISSUE THREAD

**Issue by ChrisMCMine** [crafatar/crafatar#92]
It would be nice if the endpoints accepted direct urls to a skin file beside a player name/uuid.

I guess it wouldn't consume more server resource because the raw skin has to be downloaded anyway, from a mojang server or from the url parameter.

Example:
```
https://crafatar.com/renders/body/https://i.imgur.com/E9B0424.png
```

**Comment by Jake0oo0** [comment]
Hi Chris, unfortunately, we don't directly support 3rd party skins, but you can use the default parameter. See [here](https://crafatar.com/) for more info on that. I see that you're using renders in this case, and currently, we only render default steve or alex images.

**Comment by jomo** [comment]
I think the amount people who would use this is very low, and I thus we won't be implementing this.
If you really need it, just [fork it](https://github.com/crafatar/crafatar/fork) and mess around with the [textures url](https://github.com/crafatar/crafatar/blob/103519637f43ffbfa74cf9f6b0ae849917267645/modules/networking.js#L9).
