### ISSUE TITLE
not existing uuids aren't cached

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#93]
I think it *might* have something to do with this, but I'm not sure:
https://github.com/crafatar/crafatar/blob/de5ef29c2a3703042292d5557cd2dedb6fa05545/modules/helpers.js#L36

I'm also not sure if changing that single line would work for all uses of `get_from`.

I only noticed this in the log files, might be the case for usernames as well.

**Comment by Jake0oo0** [comment]
Not sure what causes this @jomo, we still cache it, even if it's null, and it seems to work locally, as far as I can tell.

**Comment by jomo** [comment]
We were caching null skins and null capes, but if the profile is null, it didn't even get there.
